### ISSUE TITLE
No longer working?

### ISSUE THREAD

**Issue by avoqado** [SebastienWae/tiktok-gorgon-bridge#2]
Tried this method, but I think it generate wrong x-gordon.

**Comment by SebastienWae** [comment]
It's possible, it was working in October/November but I'm not working on TikTok for the moment that's why I moved this repo to public. I'll probably get back to it next month.

**Comment by SuhatAkbulak** [comment]
@SebastienWae Device_Register server ?

**Comment by drakos** [comment]
@avoqado Did you try with the same version 13.1.3 as he did?

**Comment by SebastienWae** [comment]
It should be working now.
